### ISSUE TITLE
Lets Todo in multiple languages!

### ISSUE THREAD

**Issue by sakethramanujam** [sakethramanujam/The-Todo-Multiverse#1]
- [x] Fork the repo.
- [x] Create a branch under your name.
- [x] Make a folder with the name of language ,say *React* and code a todo app.
- [x] Open a PR!

**Comment by liloo2040** [comment]
Hello! I'll be very interested ! Are some frameworks allowed ? Or is it 100 % native language ?

**Comment by sakethramanujam** [comment]
Any framework! @liloo2040 Assigning this issue to you once you've made a contrib.
